# Generated by Django 3.0.5 on 2020-04-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
